### ISSUE TITLE
Refactor camera to be attached to a doodad

### ISSUE THREAD

**Issue by Kejoko** [KingLineSoftworks/Quartz#95]
Doodads should have an optional camera component, and we should select the active camera for which we are using to render the scene.

This will allow us to shift towards the paradigm of programming all of the logic within the application, the camera shouldn't have its own movement controls.

# Todo
- [ ] Make camera attach to empty doodad
- [ ] Mimic current functionality
    - [ ] Doodad's callbacks modify the position and orientation of the doodad, thus updating the camera's position and orientation
