### ISSUE TITLE
Refactor doodad logic to be handled entirely within the Application

### ISSUE THREAD

**Issue by Kejoko** [KingLineSoftworks/Quartz#96]
Let's take all of the logic out of `Application.cpp` and actually put it into the implementation of the application.

We want to dictate what we are putting in our scene in the actual application, not the application class
- which doodads we have
- what each of the doodads contain
- what happens to the doodads when they are updated in the game loop

We will likely need to start adapting a functional programming paradigm. We are probably going to give the doodad's callbacks which they will execute during their update function. These callbacks will hold the actual game logic and will determine how the doodads behave

We can mimic the current camera behavior by attaching it to a doodad (without setting any transform offset) with no model and no rigidbody and a callback which updates its position in the same fashion that the camera does presently.

# Todo
## Scene loading and `SceneManager`
- [x] `Application` maintains a vector of scenes, so it can hold more than 1
- [x] `Application` is given a vector of `scene information` structs
- [x] `Application` gives the scene information to the `SceneManager`
- [x] `Application` initializes it's current scene when running (only load the scene when we actually need it)
    - [x] `m_scene.load(...)` with the relevant information from the `SceneManager`
## `Doodad` logic
- [ ] Give `Doodad` a fixed update callback and an update callback
    - [ ] execute fixed update callback within `Doodad::fixedUpdate`
    - [ ] execute update callback within `Doodad::update`
